const CAPTCHA_TOKEN_VERIFY_URL:string = "https://www.google.com/recaptcha/api/siteverify"
const GOOGOLE_CAPTCHA_SECRECT_KEY:string = "6LcLc5kcAAAAACv_CDsY9EkLSi1J8waZycj-mE4K"

export default {
    GOOGOLE_CAPTCHA_SECRECT_KEY: GOOGOLE_CAPTCHA_SECRECT_KEY,
    CAPTCHA_TOKEN_VERIFY_URL: CAPTCHA_TOKEN_VERIFY_URL
}